# Generated by Django 3.1.6 on 2021-02-17 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210213_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='ocuppied_by',
            new_name='occupied_by',
        ),
    ]
