# Generated by Django 3.1.6 on 2021-02-17 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210216_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False, verbose_name='id rol')),
                ('name_rol', models.CharField(max_length=20, verbose_name='Nombre de Rol')),
            ],
        ),
        migrations.AddField(
            model_name='newuser',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rol_id', to='users.rol'),
        ),
    ]
