# Generated by Django 3.1.6 on 2021-02-18 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210216_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rol', to='users.rol'),
        ),
    ]
