# Generated by Django 3.1.6 on 2021-02-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210217_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='type_obj',
            field=models.CharField(default='R', editable=False, max_length=1, verbose_name='Tipo de Objeto'),
        ),
    ]
