# Generated by Django 3.1.6 on 2021-02-18 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210217_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='type_obj',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='type_obj',
        ),
    ]
