# Generated by Django 3.1.6 on 2021-02-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210217_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='newuser',
            table='Usuarios',
        ),
    ]
