# Generated by Django 3.1.6 on 2021-04-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210224_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='id_rol',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id rol'),
        ),
    ]
