# Generated by Django 3.1.6 on 2021-02-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_int',
            field=models.CharField(blank=True, max_length=40, verbose_name='Numero Interior'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='Codigo Postal'),
        ),
    ]
