# Generated by Django 3.1.6 on 2021-02-18 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210213_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_area', models.CharField(max_length=300, verbose_name='Nombre de Area')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateField(auto_now=True, verbose_name='Fecha de ultima Modificacion')),
                ('created_by', models.CharField(max_length=10, null=True, verbose_name='Creado Por')),
                ('modified_by', models.CharField(max_length=10, null=True, verbose_name='Modificado Por')),
                ('path_img_header', models.CharField(max_length=300, null=True, verbose_name='Ruta de Imagen de Header')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id_activity', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_activity', models.CharField(max_length=300, verbose_name='Nombre de Actividad')),
                ('status', models.BooleanField(verbose_name='Estatus')),
                ('observations', models.TextField(verbose_name='Observaciones de Actividad')),
                ('path_img_header', models.CharField(max_length=300, null=True, verbose_name='Ruta de Imagen de Header')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('created_by', models.CharField(max_length=10, null=True, verbose_name='Creado Por')),
                ('modified', models.DateField(auto_now=True, verbose_name='Fecha de ultima Modificacion')),
                ('modified_by', models.CharField(max_length=10, null=True, verbose_name='Modificado Por')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Area', to='company.area')),
            ],
        ),
    ]
