# Generated by Django 3.1.6 on 2021-02-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20210217_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa'},
        ),
    ]
