# Generated by Django 3.1.6 on 2021-03-12 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_imagenactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureActivity',
            fields=[
                ('id_img', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_img', models.CharField(max_length=100, verbose_name='Nombre de Imagen')),
                ('tipo', models.CharField(max_length=100, verbose_name='tipo')),
                ('path_img', models.CharField(max_length=500, null=True, verbose_name='Ruta de Imagen')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('created_by', models.CharField(max_length=10, null=True, verbose_name='Creado Por')),
                ('modified', models.DateField(auto_now=True, verbose_name='Fecha de ultima Modificacion')),
                ('modified_by', models.CharField(max_length=10, null=True, verbose_name='Modificado Por')),
                ('Activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_imagen', to='company.activity')),
            ],
            options={
                'verbose_name': 'imagen Actividad',
                'verbose_name_plural': 'imagenes',
            },
        ),
        migrations.CreateModel(
            name='PictureActivityObservations',
            fields=[
                ('id_img', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_img', models.CharField(max_length=100, verbose_name='Nombre de Imagen')),
                ('path_img', models.CharField(max_length=500, null=True, verbose_name='Ruta de Imagen')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('created_by', models.CharField(max_length=10, null=True, verbose_name='Creado Por')),
                ('modified', models.DateField(auto_now=True, verbose_name='Fecha de ultima Modificacion')),
                ('modified_by', models.CharField(max_length=10, null=True, verbose_name='Modificado Por')),
                ('Activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_imagen', to='company.activity')),
            ],
            options={
                'verbose_name': 'imagen Observacion',
                'verbose_name_plural': 'Imagenes Observaciones',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_task', models.CharField(max_length=100, null=True, verbose_name='N')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('created_by', models.CharField(max_length=10, null=True, verbose_name='Creado Por')),
                ('modified', models.DateField(auto_now=True, verbose_name='Fecha de ultima Modificacion')),
                ('modified_by', models.CharField(max_length=10, null=True, verbose_name='Modificado Por')),
                ('Activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_tarea', to='company.activity')),
            ],
        ),
        migrations.DeleteModel(
            name='ImagenActividad',
        ),
    ]
