# Generated by Django 3.1.6 on 2021-03-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20210311_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictureactivity',
            old_name='Activity',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='pictureactivity',
            old_name='tipo',
            new_name='tipo_imagen',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Activity',
            new_name='activity',
        ),
        migrations.DeleteModel(
            name='PictureActivityObservations',
        ),
    ]
