# Generated by Django 3.1.6 on 2021-03-12 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20210311_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictureactivity',
            old_name='tipo_imagen',
            new_name='tipo_img',
        ),
    ]
