# Generated by Django 3.1.6 on 2021-03-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20210311_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observaciones de Actividad'),
        ),
        migrations.AlterField(
            model_name='pictureactivity',
            name='name_img',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de Imagen'),
        ),
    ]
