# Generated by Django 3.1.6 on 2021-03-28 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20210313_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='company.area'),
        ),
    ]
