# Generated by Django 3.1.6 on 2021-03-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20210330_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estatus'),
        ),
    ]
