# Generated by Django 3.0.2 on 2021-04-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20210404_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictureactivity',
            name='name_img',
        ),
    ]
