# Generated by Django 3.0.2 on 2021-04-13 17:43

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_remove_pictureactivity_name_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureactivity',
            name='path_img',
            field=s3direct.fields.S3DirectField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
