# Generated by Django 3.0.2 on 2021-04-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_auto_20210413_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictureactivity',
            old_name='path_img',
            new_name='img_file',
        ),
    ]
