# Generated by Django 3.0.2 on 2021-04-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20210413_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureactivity',
            name='img_file',
            field=models.ImageField(blank=True, upload_to='', verbose_name='primary_destination'),
        ),
    ]
