# Generated by Django 3.0.2 on 2021-04-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_auto_20210413_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='path_img_header',
            field=models.ImageField(blank=True, upload_to='bar'),
        ),
        migrations.AlterField(
            model_name='pictureactivity',
            name='img_file',
            field=models.ImageField(blank=True, upload_to='bar'),
        ),
    ]
