# Generated by Django 3.0.2 on 2021-04-13 18:40

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_auto_20210413_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='path_img_header',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
        migrations.AlterField(
            model_name='pictureactivity',
            name='img_file',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
