# Generated by Django 3.0.2 on 2021-04-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_auto_20210413_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='path_img_header',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='pictureactivity',
            name='img_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
