# Generated by Django 3.0.2 on 2021-04-13 22:36

from django.db import migrations, models
import django.db.models.deletion
import rest_api_crud_rwservices.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_auto_20210413_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_pictures', to='company.Activity'),
        ),
        migrations.AlterField(
            model_name='pictureactivity',
            name='img_file',
            field=models.FileField(storage=rest_api_crud_rwservices.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
