# Generated by Django 3.0.2 on 2021-04-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_auto_20210413_1736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PictureActivity',
            new_name='Picture',
        ),
    ]
