# Generated by Django 3.0.2 on 2021-04-14 03:01

from django.db import migrations, models
import rest_api_crud_rwservices.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_auto_20210413_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='path_img_header',
            field=models.ImageField(storage=rest_api_crud_rwservices.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='picture',
            name='img_file',
            field=models.ImageField(storage=rest_api_crud_rwservices.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
