# Generated by Django 3.0.2 on 2021-04-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_auto_20210413_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='path_logo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta Logo Imagen'),
        ),
    ]
