# Generated by Django 3.1.6 on 2021-02-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rfc', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='RFC')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Empresa')),
                ('second_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('second_last_name', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('curp', models.CharField(max_length=100, verbose_name='CURP')),
                ('birthday', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateField(auto_now=True, verbose_name='Fecha de ultima Modificacion')),
                ('created_by', models.CharField(max_length=10, null=True, verbose_name='Creado Por')),
                ('modified_by', models.CharField(max_length=10, null=True, verbose_name='Modificado Por')),
            ],
        ),
    ]
