# Generated by Django 3.1.6 on 2021-02-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_empleado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de Empleado'),
        ),
    ]
