# Generated by Django 3.1.6 on 2021-02-18 03:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleado', '0003_auto_20210217_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleado',
            new_name='Employee',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Empleado',
        ),
    ]
