# Generated by Django 3.1.6 on 2021-02-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_auto_20210217_2132'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Empleados',
        ),
    ]
