# Generated by Django 3.1.6 on 2021-02-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_auto_20210217_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Empleado'},
        ),
    ]
